-- =====================================================================
-- IoT Device Data Streamlining -- Star Schema (PostgreSQL)
-- =====================================================================
-- Upgrades the flat schema in 01_schema.sql to a Kimball star schema.
--
-- Run order:  01 -> 02 -> 03 -> 04 -> 05 -> 06 -> 07
--
-- This script is ADDITIVE. It creates a new `mart` schema and leaves
-- every table in `public` untouched, so the existing Power BI file and
-- the legacy Spark job keep working during the transition.
--
-- Idempotent: safe to re-run.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS mart;
SET search_path TO mart, public;

-- =====================================================================
-- SECTION 1 -- DIMENSIONS
-- =====================================================================

-- ---------------------------------------------------------------------
-- dim_date : conformed, role-playing, pre-generated 2024-2034
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_date (
    date_key          INTEGER      PRIMARY KEY,          -- YYYYMMDD
    full_date         DATE         NOT NULL UNIQUE,
    day_of_week       SMALLINT     NOT NULL,
    day_name          VARCHAR(10)  NOT NULL,
    day_of_month      SMALLINT     NOT NULL,
    day_of_year       SMALLINT     NOT NULL,
    week_of_year      SMALLINT     NOT NULL,
    iso_week          VARCHAR(10)  NOT NULL,
    month_number      SMALLINT     NOT NULL,
    month_name        VARCHAR(10)  NOT NULL,
    month_year        VARCHAR(20)  NOT NULL,
    quarter_number    SMALLINT     NOT NULL,
    quarter_name      VARCHAR(10)  NOT NULL,
    year_number       SMALLINT     NOT NULL,
    fiscal_month      SMALLINT     NOT NULL,
    fiscal_quarter    SMALLINT     NOT NULL,
    fiscal_year       SMALLINT     NOT NULL,
    is_weekend        BOOLEAN      NOT NULL,
    is_holiday        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_working_day    BOOLEAN      NOT NULL,
    month_start_date  DATE         NOT NULL,
    month_end_date    DATE         NOT NULL
);
COMMENT ON TABLE dim_date IS
    'Conformed date dimension. Mark as date table in Power BI on full_date.';

-- ---------------------------------------------------------------------
-- dim_time : minute grain, 1440 rows
-- Kept separate from dim_date deliberately: a combined datetime
-- dimension would be 3.15M rows per decade instead of 3650 + 1440.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_time (
    time_key        SMALLINT     PRIMARY KEY,            -- minutes since midnight, 0..1439
    time_value      TIME         NOT NULL,
    hour_24         SMALLINT     NOT NULL,
    hour_12         SMALLINT     NOT NULL,
    minute_of_hour  SMALLINT     NOT NULL,
    am_pm           CHAR(2)      NOT NULL,
    hour_bucket     VARCHAR(20)  NOT NULL,               -- '08:00 - 09:00'
    shift_key       SMALLINT     NOT NULL,
    day_part        VARCHAR(20)  NOT NULL
);

-- ---------------------------------------------------------------------
-- dim_shift
-- Shift boundaries are data, not hardcoded logic. Changing a shift
-- pattern becomes an UPDATE rather than a code deploy.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_shift (
    shift_key         SMALLINT     PRIMARY KEY,
    shift_code        VARCHAR(10)  NOT NULL,
    shift_name        VARCHAR(30)  NOT NULL,
    start_time        TIME         NOT NULL,
    end_time          TIME         NOT NULL,
    planned_minutes   INTEGER      NOT NULL,
    crosses_midnight  BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ---------------------------------------------------------------------
-- dim_machine : Slowly Changing Dimension Type 2
--
-- Machines get recommissioned, moved between lines and re-rated.
-- Type 2 means a reading from March is attributed to the line the
-- machine was on IN MARCH, not where it sits today.
--
-- Sources public.machines, which already carries ideal_cycle_time_sec.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_machine (
    machine_key           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id            VARCHAR(20)   NOT NULL,        -- natural key from public.machines
    machine_name          VARCHAR(100)  NOT NULL,
    machine_type          VARCHAR(50)   NOT NULL,
    location              VARCHAR(100),
    production_line       VARCHAR(50)   NOT NULL DEFAULT 'UNASSIGNED',
    plant_code            VARCHAR(20)   NOT NULL DEFAULT 'PLANT-01',
    manufacturer          VARCHAR(100),
    model_number          VARCHAR(50),
    installed_date        DATE,
    ideal_cycle_time_sec  NUMERIC(10,2) NOT NULL DEFAULT 1.0,
    rated_power_kw        NUMERIC(10,3),
    nominal_temp_c        NUMERIC(6,2),
    max_safe_temp_c       NUMERIC(6,2),
    criticality           VARCHAR(10)   NOT NULL DEFAULT 'MEDIUM',
    is_active             BOOLEAN       NOT NULL DEFAULT TRUE,
    is_inferred           BOOLEAN       NOT NULL DEFAULT FALSE,
    -- SCD2 control columns
    valid_from            TIMESTAMP     NOT NULL DEFAULT NOW(),
    valid_to              TIMESTAMP     NOT NULL DEFAULT '9999-12-31 23:59:59',
    is_current            BOOLEAN       NOT NULL DEFAULT TRUE,
    row_hash              CHAR(64),
    created_at            TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_machine_criticality CHECK (criticality IN ('HIGH','MEDIUM','LOW')),
    CONSTRAINT chk_machine_validity    CHECK (valid_to > valid_from)
);

-- Exactly one current row per natural key
CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_machine_current
    ON dim_machine (machine_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_dim_machine_natural
    ON dim_machine (machine_id, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS ix_dim_machine_rls
    ON dim_machine (plant_code, production_line);

-- ---------------------------------------------------------------------
-- dim_machine_status
-- is_planned_downtime is the column that makes OEE Availability
-- defensible: penalising a plant for scheduled maintenance makes the
-- metric useless as a management signal.
--
-- Status codes match public.sensor_readings.status:
--   RUNNING | IDLE | DOWN | FAULT
-- plus MAINTENANCE and SETUP for planned stoppage.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_machine_status (
    status_key           SMALLINT     PRIMARY KEY,
    status_code          VARCHAR(20)  NOT NULL UNIQUE,
    status_name          VARCHAR(50)  NOT NULL,
    status_category      VARCHAR(30)  NOT NULL,
    is_productive        BOOLEAN      NOT NULL,
    is_downtime          BOOLEAN      NOT NULL,
    is_planned_downtime  BOOLEAN      NOT NULL,
    counts_toward_oee    BOOLEAN      NOT NULL,
    display_colour_hex   CHAR(7),
    sort_order           SMALLINT     NOT NULL
);

-- ---------------------------------------------------------------------
-- dim_alert_type
-- alert_code values match public.failure_alerts.alert_type:
--   HIGH_TEMP | HIGH_VIBRATION | FAULT_STATUS
-- sla_response_minutes enables MTTA-versus-SLA measures.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_alert_type (
    alert_type_key        SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_code            VARCHAR(40)  NOT NULL UNIQUE,
    alert_name            VARCHAR(100) NOT NULL,
    alert_category        VARCHAR(40)  NOT NULL,
    severity              VARCHAR(20)  NOT NULL,
    severity_rank         SMALLINT     NOT NULL,
    sla_response_minutes  INTEGER      NOT NULL,
    requires_shutdown     BOOLEAN      NOT NULL DEFAULT FALSE,
    display_colour_hex    CHAR(7),
    CONSTRAINT chk_alert_severity CHECK (severity IN ('CRITICAL','HIGH','MEDIUM','LOW','INFO'))
);

-- ---------------------------------------------------------------------
-- dim_reading_flags : junk dimension
-- Collapses three low-cardinality booleans into one small dimension
-- instead of three columns on a multi-million-row fact.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_reading_flags (
    flags_key         SMALLINT     PRIMARY KEY,
    is_outlier        BOOLEAN      NOT NULL,
    is_backfilled     BOOLEAN      NOT NULL,
    is_estimated      BOOLEAN      NOT NULL,
    flag_description  VARCHAR(100) NOT NULL
);

-- =====================================================================
-- SECTION 2 -- FACTS
-- =====================================================================

-- ---------------------------------------------------------------------
-- fact_sensor_reading
-- GRAIN: one row per machine per telemetry emission.
-- Sources public.sensor_readings. Monthly range partitions.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_sensor_reading (
    reading_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    date_key         INTEGER      NOT NULL,
    time_key         SMALLINT     NOT NULL,
    machine_key      BIGINT       NOT NULL,
    status_key       SMALLINT     NOT NULL,
    shift_key        SMALLINT     NOT NULL,
    flags_key        SMALLINT     NOT NULL DEFAULT 1,
    event_ts         TIMESTAMP    NOT NULL,
    event_date       DATE         NOT NULL,
    -- measures
    temperature_c    NUMERIC(6,2),                        -- semi-additive: average, never sum
    power_kw         NUMERIC(8,3),                        -- semi-additive
    vibration_mm_s   NUMERIC(6,3),                        -- semi-additive
    units_produced   INTEGER      NOT NULL DEFAULT 0,     -- fully additive
    good_units       INTEGER      NOT NULL DEFAULT 0,     -- fully additive
    scrap_units      INTEGER      GENERATED ALWAYS AS (units_produced - good_units) STORED,
    runtime_seconds  NUMERIC(8,2) NOT NULL DEFAULT 0,
    -- lineage
    legacy_reading_id BIGINT,
    ingested_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (reading_id, event_date)
) PARTITION BY RANGE (event_date);

CREATE TABLE IF NOT EXISTS fact_sensor_reading_2026_07 PARTITION OF fact_sensor_reading
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE IF NOT EXISTS fact_sensor_reading_2026_08 PARTITION OF fact_sensor_reading
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS fact_sensor_reading_2026_09 PARTITION OF fact_sensor_reading
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS fact_sensor_reading_2026_10 PARTITION OF fact_sensor_reading
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS fact_sensor_reading_default PARTITION OF fact_sensor_reading DEFAULT;

CREATE INDEX IF NOT EXISTS ix_fsr_machine_date ON fact_sensor_reading (machine_key, event_date);
CREATE INDEX IF NOT EXISTS ix_fsr_event_ts_brin ON fact_sensor_reading USING BRIN (event_ts);
CREATE INDEX IF NOT EXISTS ix_fsr_date_key ON fact_sensor_reading (date_key);

-- ---------------------------------------------------------------------
-- fact_production_hourly
-- GRAIN: one row per machine per clock hour.
-- Replaces public.machine_kpi_1min as Power BI's primary source.
-- ~720 rows/machine/month vs ~518,000 at atomic grain.
--
-- temp_sum and reading_count are persisted so that rolling hourly rows
-- up to day/week/month produces a correct WEIGHTED average. Averaging
-- pre-computed averages is one of the most common silent BI errors.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_production_hourly (
    production_hour_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key            INTEGER       NOT NULL REFERENCES dim_date(date_key),
    time_key            SMALLINT      NOT NULL REFERENCES dim_time(time_key),
    machine_key         BIGINT        NOT NULL REFERENCES dim_machine(machine_key),
    shift_key           SMALLINT      NOT NULL REFERENCES dim_shift(shift_key),
    window_start        TIMESTAMP     NOT NULL,
    window_end          TIMESTAMP     NOT NULL,
    batch_id            VARCHAR(40),                       -- degenerate dimension
    -- additive measures
    reading_count       INTEGER       NOT NULL,
    units_produced      INTEGER       NOT NULL DEFAULT 0,
    good_units          INTEGER       NOT NULL DEFAULT 0,
    scrap_units         INTEGER       NOT NULL DEFAULT 0,
    runtime_minutes     NUMERIC(8,2)  NOT NULL DEFAULT 0,
    idle_minutes        NUMERIC(8,2)  NOT NULL DEFAULT 0,
    downtime_minutes    NUMERIC(8,2)  NOT NULL DEFAULT 0,
    planned_minutes     NUMERIC(8,2)  NOT NULL DEFAULT 60,
    energy_kwh          NUMERIC(12,4) NOT NULL DEFAULT 0,
    -- non-additive measures + re-aggregation components
    avg_temperature_c   NUMERIC(6,2),
    max_temperature_c   NUMERIC(6,2),
    temp_sum            NUMERIC(14,2),
    avg_vibration_mm_s  NUMERIC(6,3),
    max_vibration_mm_s  NUMERIC(6,3),
    alert_count         INTEGER       NOT NULL DEFAULT 0,
    created_at          TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fph_grain UNIQUE (machine_key, window_start)
);
CREATE INDEX IF NOT EXISTS ix_fph_date_machine ON fact_production_hourly (date_key, machine_key);

-- ---------------------------------------------------------------------
-- fact_alert
-- GRAIN: one row per alert OCCURRENCE (state transition into the
-- alerting condition) -- NOT one row per observation of that state.
--
-- This is the fix for the 15M-row alert count. The legacy Spark job
-- wrote a row on every micro-batch while a machine remained in FAULT.
-- uq_alert_occurrence enforces the correct grain at the DB layer so the
-- bug cannot silently return.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_alert (
    alert_id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key                 INTEGER       NOT NULL REFERENCES dim_date(date_key),
    time_key                 SMALLINT      NOT NULL REFERENCES dim_time(time_key),
    machine_key              BIGINT        NOT NULL REFERENCES dim_machine(machine_key),
    alert_type_key           SMALLINT      NOT NULL REFERENCES dim_alert_type(alert_type_key),
    shift_key                SMALLINT      NOT NULL REFERENCES dim_shift(shift_key),
    raised_at                TIMESTAMP     NOT NULL,
    acknowledged_at          TIMESTAMP,
    resolved_at              TIMESTAMP,
    -- measures
    alert_count              INTEGER       NOT NULL DEFAULT 1,
    time_to_acknowledge_min  NUMERIC(10,2),
    time_to_resolve_min      NUMERIC(10,2),
    breached_sla             BOOLEAN,
    -- attributes
    trigger_value            NUMERIC(12,3),
    threshold_value          NUMERIC(12,3),
    message                  TEXT,
    acknowledged_by          VARCHAR(100),
    legacy_alert_id          BIGINT,
    is_open                  BOOLEAN       GENERATED ALWAYS AS (resolved_at IS NULL) STORED,
    created_at               TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_alert_occurrence UNIQUE (machine_key, alert_type_key, raised_at)
);
CREATE INDEX IF NOT EXISTS ix_fact_alert_open ON fact_alert (machine_key) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_fact_alert_date ON fact_alert (date_key, machine_key);

-- ---------------------------------------------------------------------
-- fact_downtime
-- GRAIN: one row per continuous downtime episode.
-- Accumulating snapshot: inserted on start with ended_at NULL, updated
-- on recovery. Sources public.downtime_events.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_downtime (
    downtime_id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_key              INTEGER       NOT NULL REFERENCES dim_date(date_key),
    time_key              SMALLINT      NOT NULL REFERENCES dim_time(time_key),
    machine_key           BIGINT        NOT NULL REFERENCES dim_machine(machine_key),
    status_key            SMALLINT      NOT NULL REFERENCES dim_machine_status(status_key),
    shift_key             SMALLINT      NOT NULL REFERENCES dim_shift(shift_key),
    started_at            TIMESTAMP     NOT NULL,
    ended_at              TIMESTAMP,
    duration_minutes      NUMERIC(10,2),
    is_planned            BOOLEAN       NOT NULL DEFAULT FALSE,
    reason_code           VARCHAR(50),
    downtime_event_count  INTEGER       NOT NULL DEFAULT 1,
    legacy_event_id       BIGINT,
    is_open               BOOLEAN       GENERATED ALWAYS AS (ended_at IS NULL) STORED,
    created_at            TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_downtime_episode UNIQUE (machine_key, started_at)
);
CREATE INDEX IF NOT EXISTS ix_fact_downtime_open ON fact_downtime (machine_key) WHERE ended_at IS NULL;

-- =====================================================================
-- SECTION 3 -- OPERATIONAL TABLES
-- =====================================================================

CREATE TABLE IF NOT EXISTS dq_exception (
    exception_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    source_table       VARCHAR(100) NOT NULL,
    rule_name          VARCHAR(100) NOT NULL,
    severity           VARCHAR(20)  NOT NULL,
    record_identifier  TEXT,
    detail             JSONB
);

CREATE TABLE IF NOT EXISTS etl_batch_log (
    batch_log_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name       VARCHAR(100) NOT NULL,
    batch_id       VARCHAR(40),
    started_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    completed_at   TIMESTAMP,
    rows_read      BIGINT,
    rows_written   BIGINT,
    rows_rejected  BIGINT,
    status         VARCHAR(20)  NOT NULL DEFAULT 'RUNNING',
    error_detail   TEXT
);

-- ---------------------------------------------------------------------
-- Staging table for the streaming job's hourly upsert.
--
-- Defined explicitly rather than with (LIKE fact_production_hourly).
-- LIKE copies NOT NULL constraints but NOT the identity generator or
-- column defaults, so production_hour_id / alert_count / created_at all
-- arrive NULL from Spark and the batch insert is rejected with:
--   ERROR: null value in column "production_hour_id" violates not-null
--
-- Columns here are exactly what Spark writes, all nullable.
-- UNLOGGED because the contents are transient: they are merged into the
-- fact within the same batch and never need crash recovery.
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS stg_production_hourly;
CREATE UNLOGGED TABLE stg_production_hourly (
    date_key            INTEGER,
    time_key            SMALLINT,
    machine_key         BIGINT,
    shift_key           SMALLINT,
    window_start        TIMESTAMP,
    window_end          TIMESTAMP,
    reading_count       BIGINT,
    units_produced      BIGINT,
    good_units          BIGINT,
    scrap_units         BIGINT,
    runtime_minutes     DOUBLE PRECISION,
    idle_minutes        DOUBLE PRECISION,
    downtime_minutes    DOUBLE PRECISION,
    planned_minutes     DOUBLE PRECISION,
    energy_kwh          DOUBLE PRECISION,
    avg_temperature_c   DOUBLE PRECISION,
    max_temperature_c   DOUBLE PRECISION,
    temp_sum            DOUBLE PRECISION,
    avg_vibration_mm_s  DOUBLE PRECISION,
    max_vibration_mm_s  DOUBLE PRECISION
);

-- =====================================================================
-- SECTION 4 -- RESERVED "UNKNOWN" MEMBERS
--
-- Never allow NULL foreign keys. Inner joins silently drop them, which
-- converts a data-quality problem into silent under-reporting -- the
-- worst failure mode in analytics.
-- =====================================================================

INSERT INTO dim_shift (shift_key, shift_code, shift_name, start_time, end_time, planned_minutes)
VALUES (-1, 'UNK', 'Unknown', '00:00', '00:00', 0)
ON CONFLICT (shift_key) DO NOTHING;

INSERT INTO dim_machine_status
    (status_key, status_code, status_name, status_category, is_productive,
     is_downtime, is_planned_downtime, counts_toward_oee, display_colour_hex, sort_order)
VALUES (-1, 'UNKNOWN', 'Unknown', 'UNKNOWN', FALSE, FALSE, FALSE, FALSE, '#9E9E9E', 99)
ON CONFLICT (status_key) DO NOTHING;

INSERT INTO dim_reading_flags (flags_key, is_outlier, is_backfilled, is_estimated, flag_description)
VALUES (1, FALSE, FALSE, FALSE, 'Clean reading')
ON CONFLICT (flags_key) DO NOTHING;

-- =====================================================================
-- SECTION 5 -- FOREIGN KEYS ON THE PARTITIONED FACT
--
-- NOTE: PostgreSQL supports foreign keys FROM a partitioned table, but
-- NOT the NOT VALID modifier on them:
--   ERROR: cannot add NOT VALID foreign key on partitioned table
--          DETAIL: This feature is not yet supported on partitioned tables.
--
-- So these are created fully validated. That is cheap here because the
-- fact is empty at this point in the deployment order (04 runs before
-- the 06 backfill). If you ever re-add these to a populated table,
-- expect a full scan and schedule it off-peak.
-- =====================================================================

ALTER TABLE fact_sensor_reading
    DROP CONSTRAINT IF EXISTS fk_fsr_machine;
ALTER TABLE fact_sensor_reading
    ADD CONSTRAINT fk_fsr_machine FOREIGN KEY (machine_key)
    REFERENCES dim_machine(machine_key);

ALTER TABLE fact_sensor_reading
    DROP CONSTRAINT IF EXISTS fk_fsr_status;
ALTER TABLE fact_sensor_reading
    ADD CONSTRAINT fk_fsr_status FOREIGN KEY (status_key)
    REFERENCES dim_machine_status(status_key);
