-- =====================================================================
-- IoT Device Data Streamlining -- Row-Level Security (PostgreSQL)
-- =====================================================================
-- Defence in depth. Power BI RLS protects the report; this protects the
-- database if anyone connects directly with psql, DBeaver or Excel.
-- A security model that exists only in the BI tool is not a security model.
--
-- Run after 04, 05, 06.
-- =====================================================================
SET search_path TO mart, public;

-- ---------------------------------------------------------------------
-- 1. Security dimension -- single source of truth for who sees what.
--    Consumed by BOTH Postgres RLS and Power BI dynamic RLS.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_user_scope (
    user_scope_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_principal_name  VARCHAR(200) NOT NULL,     -- matches Entra ID UPN / USERPRINCIPALNAME()
    plant_code           VARCHAR(20),               -- NULL = all plants
    production_line      VARCHAR(50),               -- NULL = all lines in that plant
    role_name            VARCHAR(50)  NOT NULL,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    granted_by           VARCHAR(200),
    granted_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    review_due           DATE,
    CONSTRAINT chk_scope_role CHECK (
        role_name IN ('EXECUTIVE','PLANT_MANAGER','LINE_SUPERVISOR','MAINTENANCE_TECH','AUDITOR')
    )
);
CREATE INDEX IF NOT EXISTS ix_user_scope_upn
    ON dim_user_scope (LOWER(user_principal_name)) WHERE is_active;

COMMENT ON TABLE dim_user_scope IS
    'Access matrix. NULL plant_code = global. NULL production_line = whole plant.';

-- Example grants covering all three access tiers
INSERT INTO dim_user_scope
    (user_principal_name, plant_code, production_line, role_name, granted_by, review_due)
VALUES
    ('exec@contoso.com',      NULL,       NULL,     'EXECUTIVE',       'security@contoso.com', CURRENT_DATE + 365),
    ('plant.mgr@contoso.com', 'PLANT-01', NULL,     'PLANT_MANAGER',   'security@contoso.com', CURRENT_DATE + 180),
    ('linea.sup@contoso.com', 'PLANT-01', 'LINE-A', 'LINE_SUPERVISOR', 'security@contoso.com', CURRENT_DATE + 180),
    ('lineb.sup@contoso.com', 'PLANT-01', 'LINE-B', 'LINE_SUPERVISOR', 'security@contoso.com', CURRENT_DATE + 180)
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------
-- 2. Database roles
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iot_reader')  THEN CREATE ROLE iot_reader  NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iot_analyst') THEN CREATE ROLE iot_analyst NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iot_etl')     THEN CREATE ROLE iot_etl     NOLOGIN; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iot_admin')   THEN CREATE ROLE iot_admin   NOLOGIN; END IF;
END $$;

GRANT USAGE ON SCHEMA mart TO iot_reader, iot_analyst, iot_etl, iot_admin;
GRANT SELECT ON ALL TABLES IN SCHEMA mart TO iot_reader, iot_analyst;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA mart TO iot_etl;
GRANT ALL ON ALL TABLES IN SCHEMA mart TO iot_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA mart GRANT SELECT ON TABLES TO iot_reader, iot_analyst;

-- ---------------------------------------------------------------------
-- 3. Session context
-- The gateway / application sets this per connection:
--     SET LOCAL app.user_upn = 'linea.sup@contoso.com';
--
-- NOTE: the setting is deliberately NOT called app.current_user.
-- current_user is a reserved keyword in PostgreSQL, so
--     SET app.current_user = '...'
-- fails with: syntax error at or near "current_user".
-- Any GUC suffix that collides with a reserved word has the same problem.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION mart.current_app_user()
RETURNS TEXT LANGUAGE sql STABLE AS $$
    SELECT LOWER(COALESCE(current_setting('app.user_upn', TRUE), ''));
$$;

-- Machine keys visible to the current session user, across all three tiers
CREATE OR REPLACE FUNCTION mart.visible_machine_keys()
RETURNS TABLE (machine_key BIGINT)
LANGUAGE sql STABLE SECURITY DEFINER AS $$
    SELECT DISTINCT m.machine_key
    FROM mart.dim_machine m
    JOIN mart.dim_user_scope s
      ON s.is_active
     AND LOWER(s.user_principal_name) = mart.current_app_user()
     AND (s.plant_code      IS NULL OR s.plant_code      = m.plant_code)
     AND (s.production_line IS NULL OR s.production_line = m.production_line);
$$;

-- ---------------------------------------------------------------------
-- 4. Enable RLS and attach policies
-- ---------------------------------------------------------------------
ALTER TABLE mart.fact_sensor_reading    ENABLE ROW LEVEL SECURITY;
ALTER TABLE mart.fact_production_hourly ENABLE ROW LEVEL SECURITY;
ALTER TABLE mart.fact_alert             ENABLE ROW LEVEL SECURITY;
ALTER TABLE mart.fact_downtime          ENABLE ROW LEVEL SECURITY;
ALTER TABLE mart.dim_machine            ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS p_fsr_scope ON mart.fact_sensor_reading;
CREATE POLICY p_fsr_scope ON mart.fact_sensor_reading
    FOR SELECT TO iot_reader, iot_analyst
    USING (machine_key IN (SELECT machine_key FROM mart.visible_machine_keys()));

DROP POLICY IF EXISTS p_fph_scope ON mart.fact_production_hourly;
CREATE POLICY p_fph_scope ON mart.fact_production_hourly
    FOR SELECT TO iot_reader, iot_analyst
    USING (machine_key IN (SELECT machine_key FROM mart.visible_machine_keys()));

DROP POLICY IF EXISTS p_alert_scope ON mart.fact_alert;
CREATE POLICY p_alert_scope ON mart.fact_alert
    FOR SELECT TO iot_reader, iot_analyst
    USING (machine_key IN (SELECT machine_key FROM mart.visible_machine_keys()));

DROP POLICY IF EXISTS p_downtime_scope ON mart.fact_downtime;
CREATE POLICY p_downtime_scope ON mart.fact_downtime
    FOR SELECT TO iot_reader, iot_analyst
    USING (machine_key IN (SELECT machine_key FROM mart.visible_machine_keys()));

DROP POLICY IF EXISTS p_machine_scope ON mart.dim_machine;
CREATE POLICY p_machine_scope ON mart.dim_machine
    FOR SELECT TO iot_reader, iot_analyst
    USING (machine_key IN (SELECT machine_key FROM mart.visible_machine_keys())
           OR machine_key = -1);

-- ETL writes unrestricted
DROP POLICY IF EXISTS p_etl_fsr ON mart.fact_sensor_reading;
CREATE POLICY p_etl_fsr ON mart.fact_sensor_reading
    FOR ALL TO iot_etl USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS p_etl_fph ON mart.fact_production_hourly;
CREATE POLICY p_etl_fph ON mart.fact_production_hourly
    FOR ALL TO iot_etl USING (TRUE) WITH CHECK (TRUE);

-- Users may only see their own scope row
DROP POLICY IF EXISTS p_scope_self ON mart.dim_user_scope;
ALTER TABLE mart.dim_user_scope ENABLE ROW LEVEL SECURITY;
CREATE POLICY p_scope_self ON mart.dim_user_scope
    FOR SELECT TO iot_reader, iot_analyst
    USING (LOWER(user_principal_name) = mart.current_app_user());

-- ---------------------------------------------------------------------
-- 5. Column-level masking for the acknowledging operator (PII)
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.v_fact_alert_masked AS
SELECT
    f.alert_id, f.date_key, f.time_key, f.machine_key, f.alert_type_key,
    f.raised_at, f.acknowledged_at, f.resolved_at, f.alert_count,
    f.time_to_acknowledge_min, f.time_to_resolve_min, f.breached_sla,
    f.trigger_value, f.threshold_value, f.message, f.is_open,
    CASE
        WHEN pg_has_role(CURRENT_USER, 'iot_admin', 'MEMBER') THEN f.acknowledged_by
        ELSE REGEXP_REPLACE(COALESCE(f.acknowledged_by, ''), '(.).*(@.*)', '\1***\2')
    END AS acknowledged_by
FROM mart.fact_alert f;

GRANT SELECT ON mart.v_fact_alert_masked TO iot_reader, iot_analyst;

-- ---------------------------------------------------------------------
-- 6. Audit trail on access-matrix changes
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS security_audit_log (
    audit_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    db_user      VARCHAR(100) NOT NULL DEFAULT CURRENT_USER,
    app_user     VARCHAR(200),
    action       VARCHAR(50)  NOT NULL,
    object_name  VARCHAR(200),
    detail       JSONB
);

CREATE OR REPLACE FUNCTION mart.fn_audit_scope_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO mart.security_audit_log (app_user, action, object_name, detail)
    VALUES (mart.current_app_user(), TG_OP, 'dim_user_scope',
            to_jsonb(COALESCE(NEW, OLD)));
    RETURN COALESCE(NEW, OLD);
END $$;

DROP TRIGGER IF EXISTS trg_audit_user_scope ON mart.dim_user_scope;
CREATE TRIGGER trg_audit_user_scope
    AFTER INSERT OR UPDATE OR DELETE ON mart.dim_user_scope
    FOR EACH ROW EXECUTE FUNCTION mart.fn_audit_scope_change();

-- ---------------------------------------------------------------------
-- 7. Verification
-- ---------------------------------------------------------------------
-- SET LOCAL app.user_upn = 'linea.sup@contoso.com';
-- SET LOCAL ROLE iot_reader;
-- SELECT COUNT(*) FROM mart.fact_production_hourly;    -- LINE-A machines only
-- SELECT DISTINCT production_line FROM mart.dim_machine;
-- RESET ROLE;
--
-- CRITICAL TEST: an unmapped user must return ZERO rows, not all rows.
-- SET LOCAL app.user_upn = 'nobody@contoso.com';
-- SET LOCAL ROLE iot_reader;
-- SELECT COUNT(*) FROM mart.fact_production_hourly;    -- expect 0
-- RESET ROLE;
