-- =====================================================================
-- IoT Device Data Streamlining -- Snowflake Schema (PostgreSQL)
-- =====================================================================
-- Builds a normalised (snowflake) variant of the star schema in a
-- separate `snow` schema, populated FROM the existing `mart` star.
--
-- Purpose: side-by-side comparison. Both schemas describe the same
-- facts; only the dimension normalisation differs. Run
-- 09_schema_benchmark.sql afterwards to measure the difference.
--
-- Run order:  04 -> 05 -> 06 -> 07 -> 08 -> 09
-- Prerequisite: mart.* must be populated.
-- Idempotent: safe to re-run.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS snow;
SET search_path TO snow, mart, public;

-- =====================================================================
-- SECTION 1 -- OUTRIGGER DIMENSIONS (level 3, furthest from the fact)
-- =====================================================================

CREATE TABLE IF NOT EXISTS dim_manufacturer (
    manufacturer_key   SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_name  VARCHAR(100) NOT NULL UNIQUE,
    country            VARCHAR(50),
    support_tier       VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS dim_plant (
    plant_key   SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_code  VARCHAR(20)  NOT NULL UNIQUE,
    plant_name  VARCHAR(100),
    region      VARCHAR(50),
    timezone    VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dim_alert_category (
    alert_category_key   SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_category_code  VARCHAR(40)  NOT NULL UNIQUE,
    alert_category_name  VARCHAR(100),
    owning_team          VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dim_severity (
    severity_key    SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity_code   VARCHAR(20)  NOT NULL UNIQUE,
    severity_rank   SMALLINT     NOT NULL,
    escalation_path VARCHAR(100)
);

-- =====================================================================
-- SECTION 2 -- INTERMEDIATE DIMENSIONS (level 2)
-- =====================================================================

CREATE TABLE IF NOT EXISTS dim_machine_type (
    machine_type_key   SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_type_code  VARCHAR(50)  NOT NULL UNIQUE,
    machine_type_name  VARCHAR(100),
    manufacturer_key   SMALLINT     REFERENCES dim_manufacturer(manufacturer_key),
    asset_class        VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS dim_production_line (
    production_line_key   SMALLINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_line_code  VARCHAR(50)  NOT NULL,
    production_line_name  VARCHAR(100),
    plant_key             SMALLINT     REFERENCES dim_plant(plant_key),
    line_supervisor       VARCHAR(100),
    CONSTRAINT uq_line_per_plant UNIQUE (production_line_code, plant_key)
);

-- =====================================================================
-- SECTION 3 -- LEAF DIMENSIONS (level 1, joined directly to facts)
--
-- Note how thin these become: descriptive attributes have migrated
-- outward into the sub-dimensions above. That is the defining trait of
-- a snowflake, and the source of the extra join hops.
-- =====================================================================

CREATE TABLE IF NOT EXISTS dim_machine (
    machine_key           BIGINT        PRIMARY KEY,       -- key reused from mart.dim_machine
    machine_id            VARCHAR(20)   NOT NULL,
    machine_name          VARCHAR(100)  NOT NULL,
    machine_type_key      SMALLINT      REFERENCES dim_machine_type(machine_type_key),
    production_line_key   SMALLINT      REFERENCES dim_production_line(production_line_key),
    installed_date        DATE,
    ideal_cycle_time_sec  NUMERIC(10,2) NOT NULL DEFAULT 1.0,
    criticality           VARCHAR(10),
    valid_from            TIMESTAMP     NOT NULL DEFAULT NOW(),
    valid_to              TIMESTAMP     NOT NULL DEFAULT '9999-12-31 23:59:59',
    is_current            BOOLEAN       NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS ix_snow_machine_type ON dim_machine (machine_type_key);
CREATE INDEX IF NOT EXISTS ix_snow_machine_line ON dim_machine (production_line_key);

CREATE TABLE IF NOT EXISTS dim_alert_type (
    alert_type_key        SMALLINT     PRIMARY KEY,        -- key reused from mart.dim_alert_type
    alert_code            VARCHAR(40)  NOT NULL UNIQUE,
    alert_name            VARCHAR(100) NOT NULL,
    alert_category_key    SMALLINT     REFERENCES dim_alert_category(alert_category_key),
    severity_key          SMALLINT     REFERENCES dim_severity(severity_key),
    sla_response_minutes  INTEGER      NOT NULL
);

-- =====================================================================
-- SECTION 4 -- FACTS
--
-- Identical grain, measures and keys to the star. The ONLY difference
-- between the two schemas is dimension normalisation -- which is what
-- makes the benchmark in 09 a fair comparison.
-- =====================================================================

CREATE TABLE IF NOT EXISTS fact_production_hourly (
    production_hour_id  BIGINT        PRIMARY KEY,
    date_key            INTEGER       NOT NULL REFERENCES mart.dim_date(date_key),
    time_key            SMALLINT      NOT NULL REFERENCES mart.dim_time(time_key),
    machine_key         BIGINT        NOT NULL REFERENCES dim_machine(machine_key),
    shift_key           SMALLINT      NOT NULL REFERENCES mart.dim_shift(shift_key),
    window_start        TIMESTAMP     NOT NULL,
    window_end          TIMESTAMP     NOT NULL,
    reading_count       INTEGER       NOT NULL,
    units_produced      INTEGER       NOT NULL DEFAULT 0,
    good_units          INTEGER       NOT NULL DEFAULT 0,
    scrap_units         INTEGER       NOT NULL DEFAULT 0,
    runtime_minutes     NUMERIC(8,2)  NOT NULL DEFAULT 0,
    idle_minutes        NUMERIC(8,2)  NOT NULL DEFAULT 0,
    downtime_minutes    NUMERIC(8,2)  NOT NULL DEFAULT 0,
    planned_minutes     NUMERIC(8,2)  NOT NULL DEFAULT 60,
    energy_kwh          NUMERIC(12,4) NOT NULL DEFAULT 0,
    avg_temperature_c   NUMERIC(6,2),
    max_temperature_c   NUMERIC(6,2),
    temp_sum            NUMERIC(14,2),
    avg_vibration_mm_s  NUMERIC(6,3),
    max_vibration_mm_s  NUMERIC(6,3)
);
CREATE INDEX IF NOT EXISTS ix_snow_fph_date_machine
    ON fact_production_hourly (date_key, machine_key);

CREATE TABLE IF NOT EXISTS fact_alert (
    alert_id        BIGINT     PRIMARY KEY,
    date_key        INTEGER    NOT NULL REFERENCES mart.dim_date(date_key),
    time_key        SMALLINT   NOT NULL REFERENCES mart.dim_time(time_key),
    machine_key     BIGINT     NOT NULL REFERENCES dim_machine(machine_key),
    alert_type_key  SMALLINT   NOT NULL REFERENCES dim_alert_type(alert_type_key),
    shift_key       SMALLINT   NOT NULL REFERENCES mart.dim_shift(shift_key),
    raised_at       TIMESTAMP  NOT NULL,
    resolved_at     TIMESTAMP,
    alert_count     INTEGER    NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS ix_snow_alert_date ON fact_alert (date_key, machine_key);

-- =====================================================================
-- SECTION 5 -- POPULATE FROM THE STAR
-- Order matters: outriggers -> intermediates -> leaves -> facts.
-- =====================================================================

-- 5a. Manufacturers (derived; the star holds these inline on dim_machine)
INSERT INTO snow.dim_manufacturer (manufacturer_name, country, support_tier)
SELECT DISTINCT COALESCE(m.manufacturer, 'UNKNOWN'), 'UNKNOWN', 'STANDARD'
FROM mart.dim_machine m
WHERE m.is_current
ON CONFLICT (manufacturer_name) DO NOTHING;

-- 5b. Plants
INSERT INTO snow.dim_plant (plant_code, plant_name, region, timezone)
SELECT DISTINCT m.plant_code, m.plant_code, 'UNKNOWN', 'UTC'
FROM mart.dim_machine m
WHERE m.is_current
ON CONFLICT (plant_code) DO NOTHING;

-- 5c. Alert categories and severities
INSERT INTO snow.dim_alert_category (alert_category_code, alert_category_name, owning_team)
SELECT DISTINCT a.alert_category, a.alert_category, 'MAINTENANCE'
FROM mart.dim_alert_type a
ON CONFLICT (alert_category_code) DO NOTHING;

INSERT INTO snow.dim_severity (severity_code, severity_rank, escalation_path)
SELECT DISTINCT a.severity, MIN(a.severity_rank), 'SHIFT_SUPERVISOR'
FROM mart.dim_alert_type a
GROUP BY a.severity
ON CONFLICT (severity_code) DO NOTHING;

-- 5d. Machine types
INSERT INTO snow.dim_machine_type (machine_type_code, machine_type_name, manufacturer_key, asset_class)
SELECT DISTINCT
    m.machine_type,
    m.machine_type,
    mf.manufacturer_key,
    CASE WHEN m.criticality = 'HIGH' THEN 'CRITICAL_ASSET' ELSE 'STANDARD_ASSET' END
FROM mart.dim_machine m
LEFT JOIN snow.dim_manufacturer mf
       ON mf.manufacturer_name = COALESCE(m.manufacturer, 'UNKNOWN')
WHERE m.is_current
ON CONFLICT (machine_type_code) DO NOTHING;

-- 5e. Production lines
INSERT INTO snow.dim_production_line (production_line_code, production_line_name, plant_key, line_supervisor)
SELECT DISTINCT
    m.production_line,
    m.production_line,
    p.plant_key,
    'UNASSIGNED'
FROM mart.dim_machine m
JOIN snow.dim_plant p ON p.plant_code = m.plant_code
WHERE m.is_current
ON CONFLICT ON CONSTRAINT uq_line_per_plant DO NOTHING;

-- 5f. Machines (leaf) -- surrogate key reused so facts stay comparable
INSERT INTO snow.dim_machine (
    machine_key, machine_id, machine_name, machine_type_key,
    production_line_key, installed_date, ideal_cycle_time_sec, criticality,
    valid_from, valid_to, is_current
)
SELECT
    m.machine_key, m.machine_id, m.machine_name,
    mt.machine_type_key, pl.production_line_key,
    m.installed_date, m.ideal_cycle_time_sec, m.criticality,
    m.valid_from, m.valid_to, m.is_current
FROM mart.dim_machine m
LEFT JOIN snow.dim_machine_type mt ON mt.machine_type_code = m.machine_type
LEFT JOIN snow.dim_plant p         ON p.plant_code = m.plant_code
LEFT JOIN snow.dim_production_line pl
       ON pl.production_line_code = m.production_line AND pl.plant_key = p.plant_key
ON CONFLICT (machine_key) DO UPDATE SET
    machine_name         = EXCLUDED.machine_name,
    machine_type_key     = EXCLUDED.machine_type_key,
    production_line_key  = EXCLUDED.production_line_key,
    ideal_cycle_time_sec = EXCLUDED.ideal_cycle_time_sec,
    criticality          = EXCLUDED.criticality,
    valid_from           = EXCLUDED.valid_from,
    valid_to             = EXCLUDED.valid_to,
    is_current           = EXCLUDED.is_current;

-- 5g. Alert types (leaf)
INSERT INTO snow.dim_alert_type (
    alert_type_key, alert_code, alert_name, alert_category_key, severity_key, sla_response_minutes
)
SELECT
    a.alert_type_key, a.alert_code, a.alert_name,
    ac.alert_category_key, sv.severity_key, a.sla_response_minutes
FROM mart.dim_alert_type a
LEFT JOIN snow.dim_alert_category ac ON ac.alert_category_code = a.alert_category
LEFT JOIN snow.dim_severity       sv ON sv.severity_code = a.severity
ON CONFLICT (alert_type_key) DO UPDATE SET
    alert_name           = EXCLUDED.alert_name,
    alert_category_key   = EXCLUDED.alert_category_key,
    severity_key         = EXCLUDED.severity_key,
    sla_response_minutes = EXCLUDED.sla_response_minutes;

-- The remaining DO NOTHING clauses above are deliberate: dim_manufacturer,
-- dim_plant, dim_alert_category, dim_severity, dim_machine_type and
-- dim_production_line are pure lookups whose natural key IS their content.
-- If the key matches, the row is identical, so there is nothing to update.
-- dim_machine and dim_alert_type carry mutable attributes and must upsert.

-- 5h. Facts
--
-- MUST be DO UPDATE, not DO NOTHING.
--
-- fact_production_hourly is an ACCUMULATING fact: the streaming job
-- upserts with `units_produced = existing + EXCLUDED`, so the current
-- hour's row keeps changing while its production_hour_id stays the same.
-- With DO NOTHING, snow would silently freeze at whatever value the row
-- held during the first copy -- row counts would match perfectly while
-- the measures drifted apart. That is exactly the failure the benchmark
-- caught (rows_added=0, rows_value_changed=5).
INSERT INTO snow.fact_production_hourly
SELECT
    production_hour_id, date_key, time_key, machine_key, shift_key,
    window_start, window_end, reading_count, units_produced, good_units,
    scrap_units, runtime_minutes, idle_minutes, downtime_minutes,
    planned_minutes, energy_kwh, avg_temperature_c, max_temperature_c,
    temp_sum, avg_vibration_mm_s, max_vibration_mm_s
FROM mart.fact_production_hourly
ON CONFLICT (production_hour_id) DO UPDATE SET
    reading_count      = EXCLUDED.reading_count,
    units_produced     = EXCLUDED.units_produced,
    good_units         = EXCLUDED.good_units,
    scrap_units        = EXCLUDED.scrap_units,
    runtime_minutes    = EXCLUDED.runtime_minutes,
    idle_minutes       = EXCLUDED.idle_minutes,
    downtime_minutes   = EXCLUDED.downtime_minutes,
    planned_minutes    = EXCLUDED.planned_minutes,
    energy_kwh         = EXCLUDED.energy_kwh,
    avg_temperature_c  = EXCLUDED.avg_temperature_c,
    max_temperature_c  = EXCLUDED.max_temperature_c,
    temp_sum           = EXCLUDED.temp_sum,
    avg_vibration_mm_s = EXCLUDED.avg_vibration_mm_s,
    max_vibration_mm_s = EXCLUDED.max_vibration_mm_s;

-- fact_alert rows are immutable once raised EXCEPT for resolved_at,
-- which is set when the alert closes. DO NOTHING would leave every
-- alert permanently open in snow.
INSERT INTO snow.fact_alert
    (alert_id, date_key, time_key, machine_key, alert_type_key, shift_key,
     raised_at, resolved_at, alert_count)
SELECT
    alert_id, date_key, time_key, machine_key, alert_type_key, shift_key,
    raised_at, resolved_at, alert_count
FROM mart.fact_alert
ON CONFLICT (alert_id) DO UPDATE SET
    resolved_at = EXCLUDED.resolved_at,
    alert_count = EXCLUDED.alert_count;

-- Remove rows deleted from the star (e.g. after the downtime-grain fix,
-- which TRUNCATEd and rebuilt fact_downtime). Without this, snow keeps
-- orphans that mart no longer has.
DELETE FROM snow.fact_production_hourly s
WHERE NOT EXISTS (
    SELECT 1 FROM mart.fact_production_hourly m
    WHERE m.production_hour_id = s.production_hour_id
);

DELETE FROM snow.fact_alert s
WHERE NOT EXISTS (
    SELECT 1 FROM mart.fact_alert m WHERE m.alert_id = s.alert_id
);

ANALYZE snow.dim_machine;
ANALYZE snow.dim_machine_type;
ANALYZE snow.dim_production_line;
ANALYZE snow.fact_production_hourly;
ANALYZE snow.fact_alert;

-- =====================================================================
-- SECTION 6 -- REFRESH TRACKING
--
-- snow is a derived copy, so "how stale is it?" must be answerable.
-- Without this, drift is invisible until a comparison happens to catch it.
-- =====================================================================

CREATE TABLE IF NOT EXISTS snow.refresh_log (
    refresh_id      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refreshed_at    TIMESTAMP   NOT NULL DEFAULT NOW(),
    hourly_rows     BIGINT,
    alert_rows      BIGINT,
    machine_rows    BIGINT,
    duration_ms     NUMERIC(10,2),
    triggered_by    VARCHAR(100) DEFAULT CURRENT_USER
);

INSERT INTO snow.refresh_log (hourly_rows, alert_rows, machine_rows)
VALUES (
    (SELECT COUNT(*) FROM snow.fact_production_hourly),
    (SELECT COUNT(*) FROM snow.fact_alert),
    (SELECT COUNT(*) FROM snow.dim_machine)
);

-- ---------------------------------------------------------------------
-- Convenience wrapper: re-sync snow from mart on demand.
--
--   SELECT * FROM snow.refresh_from_star();
--
-- Re-running this whole script achieves the same thing (every statement
-- is idempotent), but the function is callable from a scheduled job
-- without shelling out to psql with a file.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION snow.refresh_from_star()
RETURNS TABLE (
    metric      TEXT,
    star_rows   BIGINT,
    snow_rows   BIGINT,
    status      TEXT
)
LANGUAGE plpgsql AS $$
DECLARE
    t0 TIMESTAMP := CLOCK_TIMESTAMP();
BEGIN
    -- Facts: upsert changed values, then drop orphans
    INSERT INTO snow.fact_production_hourly
    SELECT production_hour_id, date_key, time_key, machine_key, shift_key,
           window_start, window_end, reading_count, units_produced, good_units,
           scrap_units, runtime_minutes, idle_minutes, downtime_minutes,
           planned_minutes, energy_kwh, avg_temperature_c, max_temperature_c,
           temp_sum, avg_vibration_mm_s, max_vibration_mm_s
    FROM mart.fact_production_hourly
    ON CONFLICT (production_hour_id) DO UPDATE SET
        reading_count      = EXCLUDED.reading_count,
        units_produced     = EXCLUDED.units_produced,
        good_units         = EXCLUDED.good_units,
        scrap_units        = EXCLUDED.scrap_units,
        runtime_minutes    = EXCLUDED.runtime_minutes,
        idle_minutes       = EXCLUDED.idle_minutes,
        downtime_minutes   = EXCLUDED.downtime_minutes,
        planned_minutes    = EXCLUDED.planned_minutes,
        energy_kwh         = EXCLUDED.energy_kwh,
        avg_temperature_c  = EXCLUDED.avg_temperature_c,
        max_temperature_c  = EXCLUDED.max_temperature_c,
        temp_sum           = EXCLUDED.temp_sum,
        avg_vibration_mm_s = EXCLUDED.avg_vibration_mm_s,
        max_vibration_mm_s = EXCLUDED.max_vibration_mm_s;

    INSERT INTO snow.fact_alert
        (alert_id, date_key, time_key, machine_key, alert_type_key, shift_key,
         raised_at, resolved_at, alert_count)
    SELECT alert_id, date_key, time_key, machine_key, alert_type_key, shift_key,
           raised_at, resolved_at, alert_count
    FROM mart.fact_alert
    ON CONFLICT (alert_id) DO UPDATE SET
        resolved_at = EXCLUDED.resolved_at,
        alert_count = EXCLUDED.alert_count;

    DELETE FROM snow.fact_production_hourly s
    WHERE NOT EXISTS (SELECT 1 FROM mart.fact_production_hourly m
                      WHERE m.production_hour_id = s.production_hour_id);

    DELETE FROM snow.fact_alert s
    WHERE NOT EXISTS (SELECT 1 FROM mart.fact_alert m
                      WHERE m.alert_id = s.alert_id);

    INSERT INTO snow.refresh_log (hourly_rows, alert_rows, machine_rows, duration_ms)
    VALUES (
        (SELECT COUNT(*) FROM snow.fact_production_hourly),
        (SELECT COUNT(*) FROM snow.fact_alert),
        (SELECT COUNT(*) FROM snow.dim_machine),
        EXTRACT(EPOCH FROM (CLOCK_TIMESTAMP() - t0)) * 1000
    );

    RETURN QUERY
    SELECT 'fact_production_hourly'::TEXT,
           (SELECT COUNT(*) FROM mart.fact_production_hourly),
           (SELECT COUNT(*) FROM snow.fact_production_hourly),
           CASE WHEN (SELECT COUNT(*) FROM mart.fact_production_hourly)
                   = (SELECT COUNT(*) FROM snow.fact_production_hourly)
                THEN 'IN SYNC' ELSE 'DRIFT' END
    UNION ALL
    SELECT 'fact_alert'::TEXT,
           (SELECT COUNT(*) FROM mart.fact_alert),
           (SELECT COUNT(*) FROM snow.fact_alert),
           CASE WHEN (SELECT COUNT(*) FROM mart.fact_alert)
                   = (SELECT COUNT(*) FROM snow.fact_alert)
                THEN 'IN SYNC' ELSE 'DRIFT' END;
END $$;

COMMENT ON FUNCTION snow.refresh_from_star() IS
    'Re-syncs snow from mart. Upserts changed measures and removes orphans. '
    'Safe to call repeatedly; logs each run to snow.refresh_log.';

-- ---------------------------------------------------------------------
-- Staleness check -- run before trusting any snow query
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW snow.v_staleness AS
SELECT
    (SELECT MAX(refreshed_at) FROM snow.refresh_log)               AS last_refreshed,
    NOW() - (SELECT MAX(refreshed_at) FROM snow.refresh_log)       AS age,
    (SELECT COUNT(*) FROM mart.fact_production_hourly)
      - (SELECT COUNT(*) FROM snow.fact_production_hourly)         AS hourly_rows_behind,
    (SELECT COUNT(*) FROM mart.fact_alert)
      - (SELECT COUNT(*) FROM snow.fact_alert)                     AS alert_rows_behind,
    (SELECT COUNT(*)
     FROM mart.fact_production_hourly m
     JOIN snow.fact_production_hourly s USING (production_hour_id)
     WHERE m.units_produced IS DISTINCT FROM s.units_produced)     AS rows_with_stale_values;

COMMENT ON VIEW snow.v_staleness IS
    'How far snow has drifted from mart. rows_with_stale_values is the one '
    'that matters: row counts can match exactly while measures diverge, '
    'because fact_production_hourly accumulates in place.';

-- =====================================================================
-- SECTION 7 -- VERIFICATION
-- =====================================================================
SELECT 'snow.dim_manufacturer'     AS table_name, COUNT(*) AS rows FROM snow.dim_manufacturer
UNION ALL SELECT 'snow.dim_plant',              COUNT(*) FROM snow.dim_plant
UNION ALL SELECT 'snow.dim_machine_type',       COUNT(*) FROM snow.dim_machine_type
UNION ALL SELECT 'snow.dim_production_line',    COUNT(*) FROM snow.dim_production_line
UNION ALL SELECT 'snow.dim_machine',            COUNT(*) FROM snow.dim_machine
UNION ALL SELECT 'snow.dim_alert_category',     COUNT(*) FROM snow.dim_alert_category
UNION ALL SELECT 'snow.dim_severity',           COUNT(*) FROM snow.dim_severity
UNION ALL SELECT 'snow.dim_alert_type',         COUNT(*) FROM snow.dim_alert_type
UNION ALL SELECT 'snow.fact_production_hourly', COUNT(*) FROM snow.fact_production_hourly
UNION ALL SELECT 'snow.fact_alert',             COUNT(*) FROM snow.fact_alert
ORDER BY table_name;
