-- =====================================================================
-- Production hardening -- dead-letter queue, downtime staging, monitoring
-- =====================================================================
-- Adds the objects required to run the pipeline unattended:
--
--   1. A dead-letter table so unparseable messages are quarantined with
--      enough Kafka coordinates to be replayed, rather than dropped.
--   2. Staging tables for the streaming downtime writer, which turns
--      fact_downtime from a static backfill artefact into a live fact.
--   3. Monitoring views that answer "is the pipeline healthy?" without
--      anyone needing to remember what healthy looks like.
--
-- Idempotent. Run after 07_row_level_security.sql.
--
-- Usage:
--   Get-Content sql\10_production_hardening.sql | docker exec -i iot-postgres `
--       psql -U iot_user -d iot_dashboard
-- =====================================================================

SET search_path TO mart, public;

-- ---------------------------------------------------------------------
-- 1. Dead-letter queue
-- ---------------------------------------------------------------------
-- The previous job filtered malformed messages out with a WHERE clause.
-- That is indistinguishable from those messages never having existed: a
-- producer release that broke the payload contract would have silently
-- discarded traffic, and the only symptom would have been a fall in row
-- counts that nothing was watching.
--
-- Kafka topic, partition and offset are retained deliberately. Without
-- them a quarantined message can be inspected but not replayed.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dlq_sensor_reading (
    dlq_id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         TEXT,
    kafka_topic      TEXT,
    kafka_partition  INTEGER,
    kafka_offset     BIGINT,
    kafka_timestamp  TIMESTAMP,
    raw_payload      TEXT,
    failure_reason   TEXT         NOT NULL,
    quarantined_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    replayed_at      TIMESTAMP,
    CONSTRAINT uq_dlq_offset UNIQUE (kafka_topic, kafka_partition, kafka_offset)
);

COMMENT ON TABLE dlq_sensor_reading IS
    'Quarantined Kafka messages that failed the schema contract. '
    'Retains topic/partition/offset so a corrected payload can be replayed.';

CREATE INDEX IF NOT EXISTS ix_dlq_unreplayed
    ON dlq_sensor_reading (quarantined_at) WHERE replayed_at IS NULL;

-- ---------------------------------------------------------------------
-- 2. Downtime staging tables
-- ---------------------------------------------------------------------
-- Explicit column lists rather than (LIKE fact_downtime). CREATE TABLE
-- ... LIKE copies NOT NULL constraints but not identity columns or
-- defaults, so a staging table built that way rejects every insert with
-- "null value in column downtime_id". That exact failure cost time on
-- the hourly aggregate; it is not repeated here.
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS stg_downtime_open;
CREATE UNLOGGED TABLE stg_downtime_open (
    date_key     INTEGER,
    time_key     SMALLINT,
    machine_key  BIGINT,
    status_key   SMALLINT,
    shift_key    SMALLINT,
    started_at   TIMESTAMP,
    is_planned   BOOLEAN,
    reason_code  VARCHAR(50)
);

DROP TABLE IF EXISTS stg_downtime_close;
CREATE UNLOGGED TABLE stg_downtime_close (
    machine_key  BIGINT,
    started_at   TIMESTAMP,
    ended_at     TIMESTAMP
);

-- ---------------------------------------------------------------------
-- 3. Monitoring views
-- ---------------------------------------------------------------------

-- Pipeline freshness. The single most useful check: if the newest sensor
-- fact is older than a couple of trigger intervals, the job is dead
-- regardless of what any other metric says.
CREATE OR REPLACE VIEW v_pipeline_freshness AS
SELECT
    MAX(event_ts)                                          AS latest_reading,
    NOW() - MAX(event_ts)                                  AS lag_behind_now,
    ROUND(EXTRACT(EPOCH FROM (NOW() - MAX(event_ts))))     AS lag_seconds,
    CASE
        WHEN MAX(event_ts) IS NULL                        THEN 'NO DATA'
        WHEN NOW() - MAX(event_ts) < INTERVAL '2 minutes'  THEN 'HEALTHY'
        WHEN NOW() - MAX(event_ts) < INTERVAL '10 minutes' THEN 'DEGRADED'
        ELSE 'STALLED'
    END                                                    AS status
FROM fact_sensor_reading;

-- Batch outcomes over the last 24 hours.
CREATE OR REPLACE VIEW v_batch_health AS
SELECT
    COUNT(*)                                                  AS batches_24h,
    COUNT(*) FILTER (WHERE status = 'SUCCESS')                AS succeeded,
    COUNT(*) FILTER (WHERE status = 'FAILED')                 AS failed,
    ROUND(100.0 * COUNT(*) FILTER (WHERE status = 'SUCCESS')
          / NULLIF(COUNT(*), 0), 2)                           AS success_rate_pct,
    MAX(completed_at) FILTER (WHERE status = 'FAILED')        AS last_failure_at,
    CASE
        WHEN COUNT(*) = 0 THEN 'NO BATCHES'
        WHEN 100.0 * COUNT(*) FILTER (WHERE status = 'SUCCESS')
             / NULLIF(COUNT(*), 0) >= 99 THEN 'HEALTHY'
        WHEN 100.0 * COUNT(*) FILTER (WHERE status = 'SUCCESS')
             / NULLIF(COUNT(*), 0) >= 95 THEN 'DEGRADED'
        ELSE 'UNHEALTHY'
    END                                                       AS status
FROM etl_batch_log
WHERE started_at > NOW() - INTERVAL '24 hours';

-- Unknown-member rate. A rising figure means the dimension is missing
-- machines the producer is sending -- usually a new asset installed on
-- the floor and never registered in the master data.
CREATE OR REPLACE VIEW v_unknown_key_rate AS
SELECT
    COUNT(*)                                                  AS rows_24h,
    COUNT(*) FILTER (WHERE machine_key = -1)                  AS unknown_machine,
    COUNT(*) FILTER (WHERE status_key = -1)                   AS unknown_status,
    ROUND(100.0 * COUNT(*) FILTER (WHERE machine_key = -1 OR status_key = -1)
          / NULLIF(COUNT(*), 0), 4)                           AS unknown_pct,
    CASE
        WHEN COUNT(*) = 0 THEN 'NO DATA'
        WHEN 100.0 * COUNT(*) FILTER (WHERE machine_key = -1 OR status_key = -1)
             / NULLIF(COUNT(*), 0) < 0.1 THEN 'HEALTHY'
        ELSE 'INVESTIGATE'
    END                                                       AS status
FROM fact_sensor_reading
WHERE event_ts > NOW() - INTERVAL '24 hours';

-- Dead-letter volume. Anything above zero warrants a look; a sudden
-- jump means the payload contract changed.
CREATE OR REPLACE VIEW v_dlq_health AS
SELECT
    COUNT(*)                                                AS quarantined_24h,
    COUNT(*) FILTER (WHERE replayed_at IS NULL)             AS awaiting_replay,
    MIN(quarantined_at)                                     AS oldest_unreplayed,
    (SELECT failure_reason FROM dlq_sensor_reading
      WHERE quarantined_at > NOW() - INTERVAL '24 hours'
      GROUP BY failure_reason ORDER BY COUNT(*) DESC LIMIT 1) AS top_reason,
    CASE WHEN COUNT(*) = 0 THEN 'HEALTHY' ELSE 'INVESTIGATE' END AS status
FROM dlq_sensor_reading
WHERE quarantined_at > NOW() - INTERVAL '24 hours';

-- Downtime episodes that never closed. An episode open far longer than
-- any plausible repair is usually a missed recovery transition, not a
-- machine that is still down.
CREATE OR REPLACE VIEW v_stuck_downtime AS
SELECT
    d.downtime_id,
    m.machine_name,
    d.started_at,
    NOW() - d.started_at                                    AS open_for,
    d.reason_code,
    CASE
        WHEN NOW() - d.started_at > INTERVAL '4 hours' THEN 'STUCK'
        ELSE 'OPEN'
    END                                                     AS status
FROM fact_downtime d
JOIN dim_machine m ON m.machine_key = d.machine_key
WHERE d.ended_at IS NULL
ORDER BY d.started_at;

-- Single roll-up. This is what an operator should run each morning, and
-- what a scheduled check should alert on.
CREATE OR REPLACE VIEW v_health_dashboard AS
SELECT 'Pipeline freshness' AS check_name, status,
       'Latest reading ' || COALESCE(lag_seconds::TEXT, 'n/a') || 's ago' AS detail
FROM v_pipeline_freshness
UNION ALL
SELECT 'Batch success rate', status,
       COALESCE(success_rate_pct::TEXT, '0') || '% over ' || batches_24h || ' batches'
FROM v_batch_health
UNION ALL
SELECT 'Unknown key rate', status,
       COALESCE(unknown_pct::TEXT, '0') || '% of ' || rows_24h || ' rows'
FROM v_unknown_key_rate
UNION ALL
SELECT 'Dead-letter queue', status,
       quarantined_24h || ' quarantined, ' || awaiting_replay || ' awaiting replay'
FROM v_dlq_health
UNION ALL
SELECT 'Stuck downtime episodes',
       CASE WHEN COUNT(*) = 0 THEN 'HEALTHY' ELSE 'INVESTIGATE' END,
       COUNT(*) || ' episode(s) open over 4 hours'
FROM v_stuck_downtime WHERE status = 'STUCK';

-- ---------------------------------------------------------------------
-- 4. Retention
-- ---------------------------------------------------------------------
-- Partition detach rather than DELETE. Dropping a partition is a
-- catalogue operation; deleting 30 million rows is hours of I/O plus a
-- bloated table that still occupies the same disk until vacuumed.
CREATE OR REPLACE FUNCTION drop_sensor_partitions_older_than(months INTEGER)
RETURNS TABLE (dropped_partition TEXT) LANGUAGE plpgsql AS $$
DECLARE
    cutoff DATE := DATE_TRUNC('month', NOW()) - (months || ' months')::INTERVAL;
    part   RECORD;
BEGIN
    FOR part IN
        SELECT c.relname
        FROM pg_class c
        JOIN pg_inherits i    ON i.inhrelid = c.oid
        JOIN pg_class parent  ON parent.oid = i.inhparent
        WHERE parent.relname = 'fact_sensor_reading'
          AND c.relname ~ '^fact_sensor_reading_[0-9]{6}$'
          AND TO_DATE(RIGHT(c.relname, 6), 'YYYYMM') < cutoff
    LOOP
        EXECUTE FORMAT('DROP TABLE IF EXISTS mart.%I', part.relname);
        dropped_partition := part.relname;
        RETURN NEXT;
    END LOOP;
END;
$$;

COMMENT ON FUNCTION drop_sensor_partitions_older_than(INTEGER) IS
    'Drops sensor partitions older than N months. Verify with a SELECT '
    'against pg_inherits before running -- this is not reversible.';

\echo ''
\echo 'Production hardening applied. Health check:'
\echo '  SELECT * FROM mart.v_health_dashboard;'
